<?php

namespace Drupal\rw_generate\Form;

use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Batch\BatchBuilder;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\user\Entity\User;
use Drupal\file\Entity\File;

class DeleteGeneratedContentForm extends FormBase {

  protected $entityTypeManager;

  public function __construct(EntityTypeManagerInterface $entityTypeManager) {
    $this->entityTypeManager = $entityTypeManager;
  }

  public static function create(ContainerInterface $container) {
    return new static(
      $container->get('entity_type.manager')
    );
  }

  public function getFormId() {
    return 'rw_generate_delete_content_form';
  }

  public function buildForm(array $form, FormStateInterface $form_state) {
    $form['description'] = [
      '#type' => 'item',
      '#markup' => $this->t('This action will delete all nodes and media that were generated by the AI Content Generator user.'),
    ];

    $form['confirmation'] = [
      '#type' => 'checkbox',
      '#title' => $this->t('I understand that this action is irreversible and I want to proceed with deleting all generated content.'),
      '#required' => TRUE,
    ];

    $form['actions']['#type'] = 'actions';
    $form['actions']['submit'] = [
      '#type' => 'submit',
      '#value' => $this->t('Delete All Generated Content'),
      '#button_type' => 'danger',
    ];

    return $form;
  }

  public function submitForm(array &$form, FormStateInterface $form_state) {
    $batch_builder = (new BatchBuilder())
      ->setTitle($this->t('Deleting Generated Content'))
      ->setInitMessage($this->t('Starting deletion of generated content.'))
      ->setProgressMessage($this->t('Processed @current out of @total.'))
      ->setErrorMessage($this->t('An error occurred during deletion.'));

    $user_storage = $this->entityTypeManager->getStorage('user');
    $ai_users = $user_storage->loadByProperties(['name' => 'AI Content Generator']);
    $ai_user = reset($ai_users);

    if (!$ai_user) {
      $this->messenger()->addWarning($this->t('The "AI Content Generator" user was not found. No content to delete.'));
      return;
    }

    $operations = [];
    $entity_types = ['node', 'media'];

    foreach ($entity_types as $entity_type_id) {
      $entity_storage = $this->entityTypeManager->getStorage($entity_type_id);
      $query = $entity_storage->getQuery()
        ->condition('uid', $ai_user->id())
        ->accessCheck(FALSE);
      $ids = $query->execute();

      if (!empty($ids)) {
        $operations[] = [
          [static::class, 'deleteGeneratedEntities'],
          [$ids, $entity_type_id],
        ];
      }
    }

    if (empty($operations)) {
      $this->messenger()->addStatus($this->t('No generated content found for deletion.'));
      return;
    }

    $batch_definition = $batch_builder->toArray();
    $batch_definition['operations'] = $operations;
    $batch_definition['finished'] = [static::class, 'deleteGeneratedEntitiesFinished'];
    batch_set($batch_definition);
  }

  public static function deleteGeneratedEntities(array $ids, string $entity_type_id, &$context) {
    if (empty($context['sandbox'])) {
      $context['sandbox']['progress'] = 0;
      $context['sandbox']['max'] = count($ids);
      $context['results']['deleted_count'] = 0;
      $context['results']['entity_type_counts'] = [];
    }
     if (!isset($context['results']['entity_type_counts'][$entity_type_id])) {
        $context['results']['entity_type_counts'][$entity_type_id] = 0;
    }

    $limit = 50;
    $ids_chunk = array_slice($ids, $context['sandbox']['progress'], $limit);

    $storage = \Drupal::entityTypeManager()->getStorage($entity_type_id);
    $entities = $storage->loadMultiple($ids_chunk);

    foreach ($entities as $entity) {
      try {
        if ($entity_type_id === 'media' && $entity->hasField('field_media_image') && !$entity->get('field_media_image')->isEmpty()) {
          $file_target_id = $entity->get('field_media_image')->target_id;
          if ($file_target_id) {
            $file = File::load($file_target_id);
            if ($file) {
              $file->delete();
            }
          }
        }
        $entity->delete();
        $context['results']['deleted_count']++;
        $context['results']['entity_type_counts'][$entity_type_id]++;
      } catch (\Exception $e) {
        \Drupal::logger('rw_generate')->error('Failed to delete @type entity with ID @id: @msg', ['@type' => $entity_type_id, '@id' => $entity->id(), '@msg' => $e->getMessage()]);
      }
    }

    $context['sandbox']['progress'] += count($ids_chunk);

    if ($context['sandbox']['progress'] >= $context['sandbox']['max']) {
      $context['finished'] = 1;
    } else {
      $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
    }
  }

  public static function deleteGeneratedEntitiesFinished($success, $results, $operations) {
    $messenger = \Drupal::messenger();
    if ($success) {
      $deleted_count = $results['deleted_count'] ?? 0;
      $messenger->addStatus(\Drupal::translation()->formatPlural($deleted_count, 'One generated item deleted.', '@count generated items deleted.'));

      if (!empty($results['entity_type_counts'])) {
        foreach ($results['entity_type_counts'] as $type => $count) {
           if ($count > 0) {
             $messenger->addStatus(\Drupal::translation()->formatPlural($count, 'One @type entity deleted.', '@count @type entities deleted.', ['@type' => $type]));
           }
        }
      }
    } else {
      $messenger->addError(\Drupal::translation()->translate('Finished with an error.'));
    }
  }

}

