<?php

namespace Drupal\rw_generate\Form;

use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Batch\BatchBuilder;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Entity\EntityFieldManagerInterface;
use Drupal\Core\Entity\EntityTypeBundleInfoInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

class DeleteGeneratedContentForm extends FormBase {

  protected $entityTypeManager;
  protected $entityFieldManager;
  protected $entityTypeBundleInfo;

  public function __construct(EntityTypeManagerInterface $entityTypeManager, EntityFieldManagerInterface $entityFieldManager, EntityTypeBundleInfoInterface $entityTypeBundleInfo) {
    $this->entityTypeManager = $entityTypeManager;
    $this->entityFieldManager = $entityFieldManager;
    $this->entityTypeBundleInfo = $entityTypeBundleInfo;
  }

  public static function create(ContainerInterface $container) {
    return new static(
      $container->get('entity_type.manager'),
      $container->get('entity_field.manager'),
      $container->get('entity_type.bundle.info')
    );
  }

  protected function hasFieldOnEntityType(string $entity_type_id, string $field_name): bool {
    $bundle_info = $this->entityTypeBundleInfo->getBundleInfo($entity_type_id);
    if (empty($bundle_info)) {
      return FALSE;
    }

    foreach (array_keys($bundle_info) as $bundle_id) {
      $field_definitions = $this->entityFieldManager->getFieldDefinitions($entity_type_id, $bundle_id);
      if (isset($field_definitions[$field_name])) {
        return TRUE;
      }
    }
    return FALSE;
  }

  public function getFormId() {
    return 'rw_generate_delete_content_form';
  }

  public function buildForm(array $form, FormStateInterface $form_state) {
    $form['description'] = [
      '#type' => 'item',
      '#markup' => $this->t('This action will delete all nodes, media, and files that were generated by the RW Generate module and tagged with the "Generated" term.'),
    ];

    $form['confirmation'] = [
      '#type' => 'checkbox',
      '#title' => $this->t('I understand that this action is irreversible and I want to proceed with deleting all generated content.'),
      '#required' => TRUE,
    ];

    $form['actions']['#type'] = 'actions';
    $form['actions']['submit'] = [
      '#type' => 'submit',
      '#value' => $this->t('Delete All Generated Content'),
      '#button_type' => 'danger',
    ];

    return $form;
  }

  public function submitForm(array &$form, FormStateInterface $form_state) {
    $batch_builder = (new BatchBuilder())
      ->setTitle($this->t('Deleting Generated Content'))
      ->setInitMessage($this->t('Starting deletion of generated content.'))
      ->setProgressMessage($this->t('Processed @current out of @total.'))
      ->setErrorMessage($this->t('An error occurred during deletion.'));

    $operations = [];

    if ($this->hasFieldOnEntityType('node', 'field_rw_generated_tag')) {
      $node_storage = $this->entityTypeManager->getStorage('node');
      $nids = $node_storage->getQuery()
        ->condition('field_rw_generated_tag.entity.vid', 'rw_generated')
        ->accessCheck(FALSE)
        ->execute();

      if (!empty($nids)) {
        $operations[] = [
          [static::class, 'deleteGeneratedEntities'],
          [$nids, 'node'],
        ];
      }
    } else {
      $this->messenger()->addWarning($this->t('The "field_rw_generated_tag" field does not exist on any node bundles. Skipping node deletion.'));
    }

    $fids_to_delete = [];
    if ($this->hasFieldOnEntityType('media', 'field_rw_generated_tag')) {
      $media_storage = $this->entityTypeManager->getStorage('media');
      $mids_tagged = $media_storage->getQuery()
        ->condition('field_rw_generated_tag.entity.vid', 'rw_generated')
        ->accessCheck(FALSE)
        ->execute();

      if (!empty($mids_tagged)) {
        $tagged_media = $media_storage->loadMultiple($mids_tagged);
        foreach ($tagged_media as $media_entity) {
          if ($media_entity->hasField('field_media_image') && !$media_entity->get('field_media_image')->isEmpty()) {
            foreach ($media_entity->get('field_media_image') as $item) {
              if ($item->target_id) {
                $fids_to_delete[$item->target_id] = $item->target_id;
              }
            }
          }
        }
      }
    }

    if (!empty($fids_to_delete)) {
      $operations[] = [
        [static::class, 'deleteGeneratedEntities'],
        [array_values($fids_to_delete), 'file'],
      ];
    }

    if ($this->hasFieldOnEntityType('media', 'field_rw_generated_tag')) {
      $media_storage = $this->entityTypeManager->getStorage('media');
      $mids = $media_storage->getQuery()
        ->condition('field_rw_generated_tag.entity.vid', 'rw_generated')
        ->accessCheck(FALSE)
        ->execute();

      if (!empty($mids)) {
        $operations[] = [
          [static::class, 'deleteGeneratedEntities'],
          [$mids, 'media'],
        ];
      }
    } else {
      $this->messenger()->addWarning($this->t('The "field_rw_generated_tag" field does not exist on any media bundles. Skipping media deletion.'));
    }

    if (empty($operations)) {
      $this->messenger()->addStatus($this->t('No generated content found for deletion.'));
      return;
    }

    $batch_definition = $batch_builder->toArray();
    $batch_definition['operations'] = $operations;
    batch_set($batch_definition);
  }

  public static function deleteGeneratedEntities(array $ids, string $entity_type_id, &$context) {
    if (empty($context['sandbox']['progress'])) {
      $context['sandbox']['progress'] = 0;
      $context['sandbox']['max'] = count($ids);
      $context['results']['deleted_count'] = 0;
      $context['results']['entity_type_counts'][$entity_type_id] = 0;
    }

    $limit = 50;
    $chunks = array_chunk($ids, $limit);
    $current_chunk = $chunks[$context['sandbox']['progress']];

    $storage = \Drupal::entityTypeManager()->getStorage($entity_type_id);
    $entities = $storage->loadMultiple($current_chunk);

    foreach ($entities as $entity) {
      try {
        $entity->delete();
        $context['results']['deleted_count']++;
        $context['results']['entity_type_counts'][$entity_type_id]++;
      } catch (\Exception $e) {
        \Drupal::logger('rw_generate')->error('Failed to delete @type entity with ID @id: @msg', ['@type' => $entity_type_id, '@id' => $entity->id(), '@msg' => $e->getMessage()]);
      }
    }

    $context['sandbox']['progress']++;
    $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
  }

  public static function deleteGeneratedEntitiesFinished($success, $results, $operations) {
    $messenger = \Drupal::messenger();
    if ($success) {
      $deleted_count = $results['deleted_count'] ?? 0;
      $messenger->addStatus($this->t(\Drupal::translation()->formatPlural($deleted_count, 'One generated item deleted.', '@count generated items deleted.')));

      if (!empty($results['entity_type_counts'])) {
        foreach ($results['entity_type_counts'] as $type => $count) {
          $messenger->addStatus($this->t(\Drupal::translation()->formatPlural($count, 'One @type entity deleted.', '@count @type entities deleted.', ['@type' => $type])));
        }
      }
    } else {
      $messenger->addError($this->t(\Drupal::translation()->translate('Finished with an error.')));
    }
  }

}
